/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#00513b",
        "on-secondary-container": "#237157",
        "on-background": "#191c1d",
        "surface-bright": "#f8f9fa",
        "inverse-surface": "#2e3132",
        "secondary-container": "#a6f2d1",
        "on-tertiary-fixed-variant": "#005236",
        "on-primary-fixed-variant": "#173bab",
        "primary": "#00288e",
        "primary-fixed": "#dde1ff",
        "surface-variant": "#e1e3e4",
        "on-error-container": "#93000a",
        "surface": "#f8f9fa",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#3fd298",
        "tertiary-container": "#00563a",
        "primary-fixed-dim": "#b8c4ff",
        "on-surface-variant": "#444653",
        "on-primary-container": "#a8b8ff",
        "surface-dim": "#d9dadb",
        "secondary": "#1b6b51",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c4c5d5",
        "background": "#f8f9fa",
        "tertiary-fixed": "#6ffbbe",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#8bd6b6",
        "surface-tint": "#3755c3",
        "outline": "#757684",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#002113",
        "surface-container-low": "#f3f4f5",
        "inverse-primary": "#b8c4ff",
        "tertiary": "#003d27",
        "surface-container-highest": "#e1e3e4",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#4edea3",
        "on-primary-fixed": "#001453",
        "secondary-fixed": "#a6f2d1",
        "on-secondary-fixed": "#002116",
        "surface-container-high": "#e7e8e9",
        "inverse-on-surface": "#f0f1f2",
        "on-error": "#ffffff",
        "surface-container": "#edeeef",
        "on-surface": "#191c1d",
        "primary-container": "#1e40af"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        xs: "4px",
        lg: "24px",
        "container-max": "1280px",
        xl: "32px",
        sm: "8px",
        "2xl": "48px",
        gutter: "24px",
        md: "16px",
        "3xl": "64px",
        base: "4px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "display-kiosk": ["Inter"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "table-data": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "label-md": ["Inter"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-kiosk": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "table-data": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
